### ISSUE TITLE
Python 3.6 Support

### ISSUE THREAD

**Issue by mariofix** [mariofix/pyflowcl#9]
meh, doesn't work  
```python
Traceback (most recent call last):
  File "flow_client.py", line 2, in <module>
    from pyflowcl import Payment, Customer
  File "/home/mariofix/proyectos/pyflow/pyflowcl/Customer.py", line 48, in <module>
    Customer, Error,
NameError: name 'Customer' is not defined
```
```
$ poetry env info

Virtualenv
Python:         3.6.11
Implementation: CPython
Path:           /home/mariofix/.cache/pypoetry/virtualenvs/pyflowcl-JkIbCSv5-py3.6
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr/local
```

**Comment by mariofix** [comment]
Must fix the tests also

**Comment by mariofix** [comment]
Crear un branch para Python3.6, dejar el principal como 3.7+
